version: "3.9"

services:
  geospatial-toolkit:
    build:
      context: ../..
      dockerfile: ./modules/geospatial-toolkit/Dockerfile
      #network: sepal
    image: "openforis/geospatial-toolkit:latest"
    container_name: geospatial-toolkit
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
    name: sepal
